name: Frontend CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Instalar pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 11

    - name: Instalar dependencias
      run: pnpm install --dir discord-clone-project-fe

    - name: Validar Linter y Prettier
      run: pnpm --dir discord-clone-project-fe run lint

    - name: Verificar compilacion
      run: pnpm --dir discord-clone-project-fe build