name: Frontend CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Instalar pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 11

    # ◄ NUEVO PASO DE DIAGNÓSTICO: Nos chivará qué hay en el servidor
    - name: Ver estructura de carpetas real
      run: ls -R

    - name: Instalar dependencias
      run: pnpm install

    - name: Validar Linter y Prettier
      run: pnpm run lint

    - name: Verificar compilacion
      run: pnpm build